// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJh7UuopujXj4RlobSekC3YQqLk-tzVls',
    appId: '1:212775899647:web:dfe0606a198e3a712e17ca',
    messagingSenderId: '212775899647',
    projectId: 'todoapp-41f31',
    authDomain: 'todoapp-41f31.firebaseapp.com',
    storageBucket: 'todoapp-41f31.appspot.com',
    measurementId: 'G-CZZW1SCPMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVFTcCBA6WXbx6T4wn1wzYzaxnEkMJxtw',
    appId: '1:212775899647:android:555ab035002329a02e17ca',
    messagingSenderId: '212775899647',
    projectId: 'todoapp-41f31',
    storageBucket: 'todoapp-41f31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDE6iQvwJEuXIyHFNJKDMI7wFSRQSZIb-A',
    appId: '1:212775899647:ios:29df82bdd24dee552e17ca',
    messagingSenderId: '212775899647',
    projectId: 'todoapp-41f31',
    storageBucket: 'todoapp-41f31.appspot.com',
    iosBundleId: 'com.example.todoApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDE6iQvwJEuXIyHFNJKDMI7wFSRQSZIb-A',
    appId: '1:212775899647:ios:29df82bdd24dee552e17ca',
    messagingSenderId: '212775899647',
    projectId: 'todoapp-41f31',
    storageBucket: 'todoapp-41f31.appspot.com',
    iosBundleId: 'com.example.todoApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJh7UuopujXj4RlobSekC3YQqLk-tzVls',
    appId: '1:212775899647:web:8a2c29bd11fe37062e17ca',
    messagingSenderId: '212775899647',
    projectId: 'todoapp-41f31',
    authDomain: 'todoapp-41f31.firebaseapp.com',
    storageBucket: 'todoapp-41f31.appspot.com',
    measurementId: 'G-JJYPZN0EPK',
  );
}
